// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SimpleMailArchiver.Data;

#nullable disable

namespace SimpleMailArchiver.Data.Migrations
{
    [DbContext(typeof(ArchiveContext))]
    [Migration("20251127200153_DetectChanges")]
    partial class DetectChanges
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("SimpleMailArchiver.Data.MailMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID");

                    b.Property<string>("Attachments")
                        .HasColumnType("TEXT")
                        .HasColumnName("ATTACHMENTS");

                    b.Property<string>("BccRecipient")
                        .HasColumnType("TEXT")
                        .HasColumnName("BCC_RECIPIENT");

                    b.Property<string>("CcRecipient")
                        .HasColumnType("TEXT")
                        .HasColumnName("CC_RECIPIENT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT")
                        .HasColumnName("RECEIVE_TIME");

                    b.Property<string>("Folder")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("FOLDER");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("HASH");

                    b.Property<string>("HtmlBody")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Recipient")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("RECIPIENT");

                    b.Property<string>("Sender")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("SENDER");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("SUBJECT");

                    b.Property<string>("TextBody")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("MESSAGE");

                    b.HasKey("Id");

                    b.ToTable("MailMessages", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
