// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SimpleMailArchiver.Data;

#nullable disable

namespace SimpleMailArchiver.Data.Migrations
{
    [DbContext(typeof(ArchiveContext))]
    partial class ArchiveContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.2");

            modelBuilder.Entity("SimpleMailArchiver.Data.MailMessage", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID");

                    b.Property<string>("Attachments")
                        .HasColumnType("TEXT")
                        .HasColumnName("ATTACHMENTS");

                    b.Property<string>("BCC_recipient")
                        .HasColumnType("TEXT")
                        .HasColumnName("BCC_RECIPIENT");

                    b.Property<string>("CC_recipient")
                        .HasColumnType("TEXT")
                        .HasColumnName("CC_RECIPIENT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT")
                        .HasColumnName("RECEIVE_TIME");

                    b.Property<string>("Folder")
                        .HasColumnType("TEXT")
                        .HasColumnName("FOLDER");

                    b.Property<string>("Hash")
                        .HasColumnType("TEXT")
                        .HasColumnName("HASH");

                    b.Property<string>("HtmlBody")
                        .HasColumnType("TEXT");

                    b.Property<string>("Recipient")
                        .HasColumnType("TEXT")
                        .HasColumnName("RECIPIENT");

                    b.Property<string>("Sender")
                        .HasColumnType("TEXT")
                        .HasColumnName("SENDER");

                    b.Property<string>("Subject")
                        .HasColumnType("TEXT")
                        .HasColumnName("SUBJECT");

                    b.Property<string>("TextBody")
                        .HasColumnType("TEXT")
                        .HasColumnName("MESSAGE");

                    b.HasKey("ID");

                    b.ToTable("MailMessages", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
