publish_docker:
    if: startsWith(github.ref, 'refs/tags/v') # make sure deploy only runs on tags with version number
    runs-on: ubuntu-latest
        
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Set env
      run: |
        echo "RELEASE_VERSION=${GITHUB_REF_NAME:1}" >> $GITHUB_ENV
        echo $RELEASE_VERSION
        
    - name: Build container
      run: docker build . -t axmeyer/simplemailarchive:$RELEASE_VERSION
    
    - name: Push container
      run: | 
        echo ${{secrets.DOCKER_HUB_DEPLOY_KEY}} | docker login --username ${{secrets.DOCKER_HUB_USER}} --password-stdin
        docker push axmeyer/simplemailarchive:$RELEASE_VERSION
        docker tag axmeyer/simplemailarchive:$RELEASE_VERSION axmeyer/simplemailarchive:latest
        docker push axmeyer/simplemailarchive:latest
