name: SimpleMailArchiveBuildAndDeploy

on: [push, pull_request]
  
jobs:
    build:
        runs-on: [ubuntu-latest]
        steps:
        - name: Checkout repo
          uses: actions/checkout@v2

        - name: Build container
          run: docker build . -t axmeyer/simplemailarchive:test

        - name: Push container if release
          if: startsWith(github.ref, 'refs/tags/v') # make sure deploy only runs on tags with version number
          run: |
            echo "RELEASE_VERSION=${GITHUB_REF_NAME:1}" >> $GITHUB_ENV
            echo $RELEASE_VERSION
            docker tag axmeyer/simplemailarchive:test axmeyer/simplemailarchive:$RELEASE_VERSION
            docker push axmeyer/simplemailarchive:$RELEASE_VERSION


        - name: Push container as latest if not prerelease
          if: startsWith(github.ref, 'refs/tags/v') && "!github.event.release.prerelease"
          run: | 
            docker tag axmeyer/simplemailarchive:$RELEASE_VERSION axmeyer/simplemailarchive:latest
            docker push axmeyer/simplemailarchive:latest
